# Generated by Django 5.1.1 on 2024-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='website_compra',
            field=models.URLField(blank=True, null=True),
        ),
    ]
