# Generated by Django 5.1.1 on 2024-10-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_livro_website_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(choices=[('ebook', 'ebook'), ('paperback', 'paperback')], default='paperback', max_length=20),
        ),
    ]
