# Generated by Django 5.1.1 on 2024-10-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_livro_ano_livro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='livro',
            name='tipo',
            field=models.CharField(choices=[('ebook', 'ebook'), ('paperback', 'paperback'), ('30x30', 'Album 30x30'), ('100x100', 'Album 30x30')], default='paperback', max_length=20),
        ),
    ]
