# Generated by Django 5.1.1 on 2024-10-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_alter_livro_ano_alter_livro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
