# Generated by Django 5.1.1 on 2024-10-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0005_alter_livro_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='tipo',
            field=models.CharField(choices=[('ebook', 'ebook'), ('paperback', 'paperback')], default='paperback', max_length=20),
        ),
    ]
