# Generated by Django 5.1.1 on 2024-10-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_opcao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opcao',
            new_name='Menu',
        ),
    ]
