# Generated by Django 5.1.1 on 2024-10-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_rename_opcao_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_menu/'),
        ),
    ]
