# Generated by Django 5.1.1 on 2024-10-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0005_menu_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
