# Generated by Django 5.1.1 on 2024-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0007_alter_membro_data_entrada_alter_membro_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='data_contrato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tese',
            name='data_defesa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
