# Generated by Django 5.1.1 on 2024-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0008_alter_aluno_data_matricula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigador',
            old_name='integrado_FCT',
            new_name='integrado_fct',
        ),
        migrations.AlterField(
            model_name='membro',
            name='grupo',
            field=models.CharField(choices=[('grupo1', 'grupo1'), ('grupo2', 'grupo2'), ('grupo3', 'grupo3'), ('grupo4', 'grupo4')], max_length=10),
        ),
    ]
