# Generated by Django 5.1.1 on 2024-11-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0009_rename_integrado_fct_investigador_integrado_fct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='data_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tese',
            name='data_defesa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
