# Generated by Django 5.1.1 on 2024-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0010_alter_aluno_data_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='main_orientador',
            field=models.CharField(default='Por definir', max_length=200),
        ),
    ]
