# Generated by Django 5.1.1 on 2024-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0011_alter_tese_main_orientador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='main_orientador',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tese',
            name='titulo',
            field=models.CharField(default='Por definir', max_length=200),
        ),
    ]
